export const server = [
  { id: 0, value: "서버를 선택하세요" },
  { id: 1, value: "스카니아" },
  { id: 2, value: "베라" },
  { id: 3, value: "루나" },
  { id: 4, value: "제니스" },
  { id: 5, value: "크로아" },
  { id: 6, value: "유니온" },
  { id: 7, value: "엘리시움" },
  { id: 8, value: "이노시스" },
  { id: 9, value: "레드" },
  { id: 10, value: "오로라" },
  { id: 11, value: "아케인" },
  { id: 12, value: "노바" },
  { id: 13, value: "리부트" },
  { id: 14, value: "리부트2" },
]

export const cheatingType = [
  { id: 0, value: "거래 타입을 입력하세요" },
  { id: 1, value: "현금 거래" },
  { id: 2, value: "주문서 거래" },
  { id: 3, value: "사냥터 비매너" },
]

export const year = [
  { id: 0, value: "년도" },
  { id: 1, value: 2020 },
  { id: 2, value: 2021 },
  { id: 3, value: 2022 },
]

export const month = [
  { id: 0, value: "월" },
  { id: 1, value: "1월" },
  { id: 2, value: "2월" },
  { id: 3, value: "3월" },
  { id: 4, value: "4월" },
  { id: 5, value: "5월" },
  { id: 6, value: "6월" },
  { id: 7, value: "7월" },
  { id: 8, value: "8월" },
  { id: 9, value: "9월" },
  { id: 10, value: "10월" },
  { id: 11, value: "11월" },
  { id: 12, value: "12월" },
]

export const day = [
  { id: 0, value: "일" },
  { id: 1, value: "1일" },
  { id: 2, value: "2일" },
  { id: 3, value: "3일" },
  { id: 4, value: "4일" },
  { id: 5, value: "5일" },
  { id: 6, value: "6일" },
  { id: 7, value: "7일" },
  { id: 8, value: "8일" },
  { id: 9, value: "9일" },
  { id: 10, value: "10일" },
  { id: 11, value: "11일" },
  { id: 12, value: "12일" },
  { id: 13, value: "13일" },
  { id: 14, value: "14일" },
  { id: 15, value: "15일" },
  { id: 16, value: "16일" },
  { id: 17, value: "17일" },
  { id: 18, value: "18일" },
  { id: 19, value: "19일" },
  { id: 20, value: "20일" },
  { id: 21, value: "21일" },
  { id: 22, value: "22일" },
  { id: 23, value: "23일" },
  { id: 24, value: "24일" },
  { id: 25, value: "25일" },
  { id: 26, value: "26일" },
  { id: 27, value: "27일" },
  { id: 28, value: "28일" },
  { id: 29, value: "29일" },
  { id: 30, value: "30일" },
  { id: 31, value: "31일" },
]